Add configurable stars in background
tobiasbp/python-arcade-tuesday-02 pull request #119
Opened 2023-02-07 21:16 UTC by tobiasbp

2023-02-09 08:36 UTC, ivan-BRHM reviewed
I personally think we should have the stars fade in and out rather than blinking. And then after this merge we need extensive reformating of the project.

2023-02-09 22:16 UTC, tobiasbp commented
> I personally think we should have the stars fade in and out rather than blinking. And then after this merge we need extensive reformating of the project.

I have pushed an update with fading stars. Let me know what you think.

2023-02-13 09:03 UTC, ivan-BRHM requested changes
one little thing

2023-02-15 07:59 UTC, tobiasbp commented on game_sprites.py
> +        self.fade_speed = random() / 30
Yes. I'll polish and put values in the config.

2023-02-21 17:09 UTC, merged