GUI Buttons for the start and Game over screens.
tobiasbp/python-arcade-tuesday-02 pull request #122
Opened 2023-02-24 18:09 UTC by Ashthecool

- Made GUI Buttons for Start screen and Game Over screens.
- Made when they are hovered change texture.

*Find problems or ideas*

2023-02-28 15:58 UTC, tobiasbp requested changes

2023-02-28 15:58 UTC, tobiasbp commented on my_game.py
> -    def on_key_press(self, symbol: int, modifiers: int):
Hey! Don't remove the press key to play feature :(

2023-02-28 15:58 UTC, tobiasbp commented on my_game.py
> -        self.new_game()
Don remove the press any key feature to start feature.

2023-03-03 08:56 UTC, TheRiddler4K commented
I got the idea that if we made a basic texture that all buttons use and then used the gui module to write text on top of it, it would be much easier to add more buttons AND these buttons could be used for the SettingsView buttons too

2023-03-05 20:36 UTC, tobiasbp approved these changes
Good addition. Thanks.

2023-03-06 06:45 UTC, merged