Merge pull request #25 from tobiasbp/main
tobiasbp/python-arcade-tuesday-02 pull request #26
Opened 2022-08-23 20:03 UTC by Ashthecool

The player floats through space, it glides and wont stop until you turn or press down, with is a break. The player will go the direction you are facing. Got the information from here: [https://api.arcade.academy/en/latest/examples/sprite_move_angle.html#sprite-move-angle](url)

2022-08-23 20:13 UTC, tobiasbp requested changes
We don't want your .idea dir in our code. It's a folder used by your local pycharm.
Changes in the PR should be for my_game.py only.

2022-08-23 20:15 UTC, Ashthecool commented
> We don't want your .idea dir in our code. It's a folder used by your local pycharm. Changes in the PR should be for my_game.py only.

How do I do that? T.T

2022-08-23 20:15 UTC, Ashthecool commented
>

2022-08-23 20:34 UTC, tobiasbp requested changes
Take a look at my comments.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +        self.drag = 0.05
No drag in space.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +        self.opposite_angle = 0
Sounds like stuff which should be in the Player class.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +            center_y=SCREEN_WIDTH//2
Don't change these. It's not part of your feature.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> -PLAYER_START_Y = 50
Don't remove these. It's not part of your feature.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +            "SCORE: {}".format(self.opposite_angle),  # Text to show
Angle should not be showed as score. Please remove the above changes.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +            self.player_sprite.change_x = round(self.joystick.x) * 4
Don't do this. We want to keep using that variable.

2022-08-23 20:34 UTC, tobiasbp commented on my_game.py
> +                self.player_sprite.speed += 0.05
We don't want magic numbers here. Please use variables. I'm pretty sure you added those values to the Player class in lines 50 to 52.

2022-08-23 20:50 UTC, tobiasbp requested changes

2022-08-23 20:50 UTC, tobiasbp commented on my_game.py
> +        self.max_speed = 5
max_speed is never used?

2022-08-31 11:49 UTC, tobiasbp requested changes

2022-08-31 11:49 UTC, tobiasbp commented on my_game.py
> +                self.player_sprite.speed += 0.05
The 0.05 need to go in to a variable. Let's make a global variable PLAYER_THRUST, and use that here.

At beginning of file:
PLAYER_THRUST = 0.05

Then use that variable here.

2022-08-31 11:49 UTC, tobiasbp commented on my_game.py
> +        self.space_pressed = None
Should be _False_, non _None_.

2022-08-31 11:49 UTC, tobiasbp commented on my_game.py
> +PLAYER_SPEED = 3
_PLAYER_SPEED_ is not used. Please remove it. I think your editor also warns you about this.

2022-08-31 20:14 UTC, tobiasbp approved these changes
Looks good. Now, let's merge it it.

2022-08-31 20:19 UTC, merged