Intro mode
tobiasbp/python-arcade-tuesday-02 pull request #54
Opened 2022-09-24 14:14 UTC by ivan-BRHM

#14
Finished the intro mode/intro screen. Made graphics for them as well as interaction with them to start the game - that being all features needed. Code might need some refactoring...

2022-09-26 13:05 UTC, tobiasbp requested changes
Looks good. Only a few minor changes needed.

2022-09-26 18:02 UTC, ivan-BRHM commented on my_game.py
>  class MyGame(arcade.Window):
you mean like this?
`class GameState(Enum):
    """
    the state of the game: INTRO, IN_GAME or GAME_OVER
    """

    INTRO
    IN_GAME
    GAME_OVER`

2022-09-27 07:09 UTC, tobiasbp commented on my_game.py
>  class MyGame(arcade.Window):
Hmmm.... Actually I mean:
```
from enum import Enum, auto

INTRO = auto()
...
...

```

2022-09-27 07:38 UTC, ivan-BRHM commented on my_game.py
>  class MyGame(arcade.Window):
like this?

`    INTRO = auto()
    IN_GAME = auto()
    GAME_OVER = auto()`

2022-09-27 10:42 UTC, tobiasbp commented on my_game.py
>  class MyGame(arcade.Window):
yes

2022-09-27 11:34 UTC, tobiasbp requested changes
Looks great. One minor thing left.

2022-09-27 11:34 UTC, tobiasbp commented on my_game.py
Maybe you could put in a placeholder here for state _GAME_OVER_? Just put _pass_ in the _elif_ block.

2022-09-27 15:09 UTC, tobiasbp approved these changes

2022-09-27 15:13 UTC, merged